"""
LLMs.txt Endpoint
=================

Serves machine-readable documentation for AI assistants.
The llms.txt file helps LLMs understand how to use this service
without additional context in prompts.

Similar to robots.txt for search engines, llms.txt tells AI
assistants what capabilities are available and how to use them.

Endpoint:
    GET /llms.txt
"""

from fastapi import APIRouter
from fastapi.responses import PlainTextResponse

router = APIRouter(tags=["Documentation"])


LLMS_TXT = """# DeskCloud MCP

> A Model Context Protocol (MCP) server that provides Claude-powered virtual desktop capabilities.
> Each session gets an isolated virtual desktop (Linux) with browser, terminal, and desktop apps.

## MCP Endpoint

Connect via MCP at: /mcp (streamable-http transport)

For Cursor IDE, add to `.cursor/mcp.json`:
```json
{
  "mcpServers": {
    "deskcloud-mcp": {
      "url": "https://your-server-url/mcp",
      "transport": "streamable-http"
    }
  }
}
```

## Available Tools (5)

### create_session
Create a new session with isolated virtual desktop.
- `title` (optional, string): Human-readable session name
- `model` (optional, string): Claude model (default: claude-sonnet-4-5-20250929)
- `system_prompt_suffix` (optional, string): Additional agent instructions
- Returns: `session_id`, `vnc_url`, `status`, `created_at`, `ttl_remaining_seconds`

### execute_task
Execute a task in a session. The agent controls the desktop to complete the task.
- `session_id` (required, string): Session to use
- `task` (required, string): Natural language task description
- Returns: `status`, `result`, `screenshots`, `tool_uses`, `duration_seconds`
- **Note**: This is a long-running operation (may take several minutes)

### get_session_status
Get current status of a session.
- `session_id` (required, string): Session to check
- Returns: `status`, `title`, `model`, `vnc_url`, `message_count`, `last_activity`, `ttl_remaining_seconds`

### destroy_session
Destroy a session and free resources.
- `session_id` (required, string): Session to destroy
- Returns: `success`, `message`

### take_screenshot
Capture current state of session's desktop.
- `session_id` (required, string): Session to screenshot
- Returns: `image_base64` (PNG), `format`, `width`, `height`

## Session Lifecycle

- Sessions auto-destroy after 1 hour of inactivity (TTL)
- Use `destroy_session` to manually clean up when done
- Each session uses ~100MB RAM (Xvfb + browser)
- Max concurrent sessions depends on server resources
- **Important**: Keep track of your `session_id` from `create_session` - there is no list_sessions tool for security reasons

## Example Workflow

1. Call `create_session` to get a `session_id`
2. Call `execute_task` with the `session_id` and your task description
3. The agent will work autonomously, using the virtual desktop
4. Optionally call `take_screenshot` to see current state
5. Call `destroy_session` when done (or let it auto-expire after 1 hour)

## Example Tasks

Good task descriptions are specific and actionable:
- "Go to amazon.com and search for wireless headphones under $50"
- "Open Firefox, navigate to google.com, and search for weather in Tokyo"
- "Create a new text file on the desktop called notes.txt with the content 'Hello World'"
- "Open the terminal and run 'ls -la' to list files"

## Limitations

- Sessions timeout after 1 hour of inactivity
- Long tasks may take several minutes to complete
- Each session is isolated (no shared state between sessions)
- Desktop resolution: 1024x768 (configurable)
- Network access depends on server configuration

## Links

- MCP Endpoint: /mcp
- REST API Documentation: /docs
- OpenAPI Specification: /openapi.json
- Health Check: /api/v1/health
- Readiness Probe: /api/v1/health/ready

## REST API Alternative

If MCP is not available, the same functionality is accessible via REST API:

- `POST /api/v1/sessions` - Create session
- `GET /api/v1/sessions` - List sessions
- `GET /api/v1/sessions/{id}` - Get session with messages
- `DELETE /api/v1/sessions/{id}` - Delete session
- `POST /api/v1/sessions/{id}/messages` - Send message (start task)
- `GET /api/v1/sessions/{id}/stream` - SSE stream for real-time updates

See /docs for full REST API documentation.

## Support

This is an open-source project. For issues and contributions:
- GitHub: https://github.com/deskcloud/deskcloud-mcp

---
Generated by DeskCloud MCP
"""


@router.get(
    "/llms.txt",
    response_class=PlainTextResponse,
    summary="LLMs.txt Documentation",
    description="Machine-readable documentation for AI assistants.",
)
async def get_llms_txt() -> str:
    """
    Serve llms.txt for LLM discoverability.
    
    This file helps AI assistants understand how to use
    this MCP server without additional context in prompts.
    
    Returns:
        Plain text documentation in llms.txt format
    """
    return LLMS_TXT
